### ISSUE TITLE
Support periods (.) for Book.Verse separations

### ISSUE THREAD

**Issue by entupo** [jdrbrn/obsidian-scripture-indexer#1]
Do you think you could support periods for separating books and verses? 

This is sometimes used and I personally use this verse notation in Obsidian since it allows me to create notes (where colons are disallowed) like this `Gen 1.1.md` Right now here's how it indexes my notes. In this case it's just capturing chapters and not verses.

<img width="674" alt="Screenshot 2024-10-14 at 12 00 27 PM" src="https://github.com/user-attachments/assets/de9b7d6d-5826-41ee-bb84-94d569ec9c4e">

**Comment by jdrbrn** [comment]
Yeah I can definitely look into this

**Comment by jdrbrn** [comment]
Added support for it in the Regex. It'll be in the next release, but it might be a bit because I think there's a performance issue I need to look into as well.

Edit: Released in 1.2.0

**Comment by jdrbrn** [comment]
I added support to the regex, but didn't actually add support to the parser. Working on that now.

**Comment by jdrbrn** [comment]
Merged into Issue #4
