### ISSUE TITLE
FR- exclude folders

### ISSUE THREAD

**Issue by acepelon** [jdrbrn/obsidian-scripture-indexer#2]
Absolutely amazing!  I have been doing a complicated query block to pull referenced scriptures from my notes together in one spot.  This looks like my work may no longer be necessary!

Since my vault has all kinds of things in it, can I request a feature to remove indexing from particular folders?  In my case, I have the Bible in a particular folder and I don't need references to the Bible chapters themselves as I already know the verses are in the Bible- I am only interested in the references from my notes folders.  I imagine this could help with indexing speed as well.

Thanks!
ACE

**Comment by jdrbrn** [comment]
Sorry for the delay, but 1.3.0 now has support for adding files or folders to an exclusion list.
